apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: annotation-setting-mcnav-link-group
spec:
  targetRef:
    group: core.halo.run
    kind: LinkGroup
  formSchema:
    - $formkit: "text"
      name: "icon"
      label: "图标"
      value: ""
      help: 图标库：https://fontawesome.com/
    - $formkit: radio
      name: show_on_navbar
      label: 显示在navbar中
      help: 控制此分组是否显示
      value: "true"
      options: 
        - label: 显示
          value: "true"
        - label: 不显示
          value: "false"

---

apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: annotation-setting-mcnav-link
spec:
  targetRef:
    group: core.halo.run
    kind: Link
  formSchema:
    - $formkit: text
      name: icon
      label: 图标
      value: ''
      help: 图标库：https://fontawesome.com/
    - $formkit: postSelect
      name: to_post
      label: 关联的文章
      help: "当有关联的文章时，则跳转到对应文章，而不是直接访问地址"

---

apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: annotation-setting-mcnav-menu
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: "text"
      name: "icon"
      label: "图标"

---

apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: annotation-setting-mcnav-post
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: "select"
      name: "mcnav_post_type"
      id: "mcnav_post_type"
      value: "url"
      label: "链接类型"
      options:
        - label: 链接
          value: "url"
        - label: 二维码
          value: "qrcode"
    - $formkit: "text"
      if: "$get(mcnav_post_type).value == 'url'"
      name: "mcnav_post_url"
      key: "mcnav_post_url"
      label: "链接"
    - $formkit: "text"
      if: "$get(mcnav_post_type).value == 'qrcode'"
      name: "mcnav_post_qrcode"
      key: "mcnav_post_qrcode"
      label: "小程序二维码"
