apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-mcnav-setting
spec:
  forms:
    - group: basic
      label: 基础设置
      formSchema:
        - $formkit: repeater
          name: tools
          label: 工具
          value:
            - url: "https://www.hsmy.fun"
              name: "热榜速览"
              icon: "fas fa-fire"
              background: "linear-gradient(45deg, #97b3ff, #2f66ff)"
            - url: "https://ditu.amap.com/"
              name: "地图"
              icon: "fas fa-fire"
              background: "red"
            - url: "https://filehelper.weixin.qq.com"
              name: "微信文件助手"
              icon: "fab fa-weixin"
              background: "#1ba784"
          children:
            - $formkit: text
              name: name
              label: 名称
            - $formkit: url
              name: url
              label: 链接
            - $formkit: text
              name: icon
              label: 图标
            - $formkit: text
              name: background
              label: 背景颜色
        - $formkit: repeater
          name: search
          label: 搜索引擎链接
          value:
            - url: "https://www.google.com/search?q="
              name: "谷歌"
              icon: "fab fa-google"
            - url: "https://yandex.com/search/?text="
              name: "Yandex"
              icon: "fab fa-yandex"
            - url: "https://github.com/search?q="
              name: "Github"
              icon: "fab fa-github"
          children:
            - $formkit: text
              name: icon
              label: 图标
            - $formkit: text
              name: name
              label: 名称
            - $formkit: url
              name: url
              label: 链接
        - $formkit: number
          name: copyright
          label: 版权号
          value: 2024
          help: 填写年份（数字）即可
        - $formkit: group
          name: beian
          label: 备案信息
          children:
            - $formkit: text
              name: index_icp
              label: 备案号
              help: 在中国大陆可以访问的网站应填写备案号
            - $formkit: text
              name: index_icp2
              label: 公安备案
              help: 在中国大陆可以访问的网站应填写公安备案号
